mixed-port: 7890
allow-lan: false
bind-address: 127.0.0.1
mode: global
log-level: info
external-controller: 127.0.0.1:9090
secret: ''
proxy-providers:
  wechat:
    type: http
    url: https://1da5d8a2743d.ai-163cdn.com/sub?target=clash&new_name=true&emoji=true&clash.doh=true&filename=YToo_SS&udp=false&url=https%3A%2F%2Fapi.ytoo.xyz%2Fosubscribe.php%3Fsid%3D130335%26token%3DG9MmudNIRh1PtQPnY6Ix%26sip002%3D1
    interval: 3600
    path: /home/lht/bfile/mihomo/wechat/providers/wechat.yaml
proxy-groups:
  - name: Proxy
    type: select
    use:
      - wechat
tun:
  enable: true
  stack: system
  device: mihomo
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
dns:
  enable: true
  listen: 127.0.0.1:1053
  enhanced-mode: fake-ip
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - 1.1.1.1
    - 8.8.8.8
